import React, { useEffect, useRef, useState } from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { useAuth } from '../features/auth/hooks/useAuth'
import Loading from '../routes/Loading'

const sections = [
  {
    icon: 'bi-file-earmark-text-fill',
    title: 'Acceptance of Terms',
    content: (
      <>
        <p>
          By accessing or using <strong>PrepAI</strong> ("the Platform"), you confirm that you have read,
          understood, and agree to be bound by these Terms and Conditions. If you do not agree to any part
          of these terms, you must discontinue use of the Platform immediately.
        </p>
        <div className="tc-highlight">
          These Terms constitute a legally binding agreement between you and PrepAI. Your continued use of
          the Platform following any updates constitutes acceptance of the revised terms.
        </div>
      </>
    ),
  },
  {
    icon: 'bi-gift-fill',
    title: 'Free Service',
    content: (
      <>
        <p>
          PrepAI is a <strong>completely free platform</strong>. There are no subscription fees, no hidden
          charges, and no premium tiers. All features are available to every user at no cost.
        </p>
        <ul className="tc-list">
          <li>No credit card or payment information is ever required.</li>
          <li>All four AI-generated outputs — Match Score, Technical Questions, Behavioral Questions, and Roadmap — are freely accessible.</li>
          <li>We reserve the right to introduce optional features in the future, but core functionality will remain free.</li>
        </ul>
      </>
    ),
  },
  {
    icon: 'bi-person-badge-fill',
    title: 'Eligibility & Account',
    content: (
      <>
        <p>To use PrepAI, you must:</p>
        <ul className="tc-list">
          <li>Be at least <strong>13 years of age</strong> (or the minimum age required in your jurisdiction).</li>
          <li>Provide accurate resume and job information to receive meaningful AI results.</li>
          <li>Be responsible for all activity that occurs under your account.</li>
          <li>Notify us immediately of any unauthorized use of your account.</li>
        </ul>
        <p>
          We reserve the right to suspend or terminate any account that violates these terms or engages
          in abusive or harmful activity.
        </p>
      </>
    ),
  },
  {
    icon: 'bi-layout-text-window-reverse',
    title: 'How the Platform Works',
    content: (
      <>
        <p>
          PrepAI analyses three inputs you provide — your <strong>Resume</strong>, a <strong>Self Description</strong>,
          and the <strong>Job Description</strong> of the role you are targeting — and generates a personalized
          interview preparation report containing:
        </p>
        <ul className="tc-list">
          <li><strong>Match Score</strong> — an AI-evaluated compatibility score between your profile and the job.</li>
          <li><strong>Technical Questions</strong> — role-specific technical interview questions based on the job requirements.</li>
          <li><strong>Behavioral Questions</strong> — soft-skill and situational questions tailored to your background.</li>
          <li><strong>Roadmap</strong> — a personalized action plan highlighting skill gaps and areas to prepare before the interview.</li>
        </ul>
        <div className="tc-highlight">
          All outputs are generated in real-time based solely on the inputs you provide in that session.
          No data from previous sessions is used or retained.
        </div>
      </>
    ),
  },
  {
    icon: 'bi-robot',
    title: 'AI-Generated Content',
    content: (
      <>
        <p>
          All reports generated by PrepAI are produced using <strong>AI language models</strong> and are
          intended for interview preparation and informational purposes only.
        </p>
        <div className="tc-highlight">
          PrepAI does not guarantee the accuracy, completeness, or fitness of AI-generated content for any
          specific role, employer, or industry. You should treat AI output as a <strong>preparation aid</strong>,
          not a definitive assessment of your qualifications or guaranteed interview questions.
        </div>
        <p>
          We are not liable for any employment decisions — yours or an employer's — made based on
          AI-generated reports or scores.
        </p>
      </>
    ),
  },
  {
    icon: 'bi-shield-check',
    title: 'Permitted Use',
    content: (
      <>
        <p>
          PrepAI grants you a limited, non-exclusive, non-transferable license to use the Platform for
          personal, non-commercial interview preparation. You agree <strong>not</strong> to:
        </p>
        <ul className="tc-list">
          <li>Reproduce, resell, or distribute AI-generated reports commercially without written consent.</li>
          <li>Use automated tools, bots, or scrapers to bulk-generate reports or extract Platform data.</li>
          <li>Upload fabricated, false, or intentionally misleading resume or job description content.</li>
          <li>Attempt to reverse-engineer, tamper with, or exploit the AI pipeline.</li>
          <li>Use the Platform for any unlawful or unauthorized purpose.</li>
        </ul>
      </>
    ),
  },
  {
    icon: 'bi-c-circle-fill',
    title: 'Intellectual Property',
    content: (
      <>
        <p>
          All Platform content, trademarks, logos, and software are the exclusive property of PrepAI or
          its licensors and are protected by applicable intellectual property laws.
        </p>
        <p>
          You retain full ownership of the content you submit (resume, self description, job description).
          By submitting content, you grant PrepAI a limited, royalty-free license to process it
          <strong> solely</strong> to generate your report — nothing more.
        </p>
        <p>
          AI-generated reports are for your personal interview preparation only and may not be
          commercially redistributed or published without permission.
        </p>
      </>
    ),
  },
  {
    icon: 'bi-exclamation-triangle-fill',
    title: 'Disclaimers & Limitation of Liability',
    content: (
      <>
        <div className="tc-highlight">
          The Platform is provided <strong>"as is"</strong> and <strong>"as available"</strong> without
          warranties of any kind — express or implied — including merchantability, fitness for a particular
          purpose, or non-infringement.
        </div>
        <p>
          To the maximum extent permitted by law, PrepAI shall not be liable for any indirect, incidental,
          special, or consequential damages arising from your use of — or inability to use — the Platform,
          including any reliance on Match Scores, Questions, or Roadmap content.
        </p>
      </>
    ),
  },
  {
    icon: 'bi-globe',
    title: 'Governing Law',
    content: (
      <>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the jurisdiction
          in which PrepAI operates, without regard to its conflict of law provisions.
        </p>
        <p>
          Any disputes shall first be attempted to be resolved through good-faith negotiation. If
          unresolved, disputes shall be subject to the exclusive jurisdiction of the competent courts
          in our operating jurisdiction.
        </p>
      </>
    ),
  },
  {
    icon: 'bi-envelope-fill',
    title: 'Contact & Notices',
    content: (
      <>
        <p>
          For any questions, concerns, or legal notices regarding these Terms, please contact us:
        </p>
        <ul className="tc-list">
          <li><strong>Email:</strong> <a href="mailto:legal@yourapp.com">legal@yourapp.com</a></li>
          <li><strong>Response time:</strong> We aim to respond to all legal inquiries within 5 business days.</li>
          <li><strong>Updates:</strong> Changes to these Terms will be posted on this page with a revised "Last Updated" date.</li>
        </ul>
      </>
    ),
  },
]

const quickNav = [
  'Acceptance of Terms',
  'Free Service',
  'Eligibility & Account',
  'How the Platform Works',
  'AI-Generated Content',
  'Permitted Use',
  'Intellectual Property',
  'Disclaimers & Liability',
  'Governing Law',
  'Contact & Notices',
]

const TermsAndCondition = () => {
  const { loading } = useAuth();
  const sectionRefs = useRef([])

  // ─── Modal State ───────────────────────────────────────────────
  const [showModal, setShowModal]     = useState(false)
  const [check1, setCheck1]           = useState(false)
  const [check2, setCheck2]           = useState(false)
  const [showWarn, setShowWarn]       = useState(false)
  const [showSuccess, setShowSuccess] = useState(false)

  // ─── Handlers ──────────────────────────────────────────────────
  const handleAgree = () => {
    if (!check1 || !check2) {
      setShowWarn(true)
      return
    }
    setShowWarn(false)
    setShowSuccess(true)
  }

  const handleCancel = () => {
    setShowModal(false)
    setCheck1(false)
    setCheck2(false)
    setShowWarn(false)
    setShowSuccess(false)
  }

  const handleOk = () => {
    setShowSuccess(false)
    setShowModal(false)
    setCheck1(false)
    setCheck2(false)
  }

  // ─── Scroll lock when model is open ────────────────────────────────────
  useEffect(() => {
    document.body.style.overflow = showModal ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [showModal])

  // ─── Intersection Observer ────────────────────────────────────
  useEffect(() => {
    if (loading) return
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('tc-section--visible')
          }
        })
      },
      { threshold: 0.08 }
    )
    sectionRefs.current.forEach((el) => el && observer.observe(el))
    return () => observer.disconnect()
  }, [loading])

  const scrollTo = (e, index) => {
    e.preventDefault()
    sectionRefs.current[index]?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  if (loading) { return <Loading /> }
  
  return (
    <div className="overflow-x-hidden position-relative">
      {/* Background Effects */}
      <div className="bg-orb orb-1"></div>
      <div className="bg-orb orb-2"></div>
      <div className="bg-orb orb-3"></div>
      <div className="grid-overlay"></div>

      <div className="container position-relative terms-section">
        <Navbar />

        {/* ─── HERO ─── */}
        <div className="tc-hero-section">
          <div className="tc-eyebrow">
            <i className="bi bi-file-earmark-text"></i>
            Legal Document
          </div>
          <h1 className="tc-hero-title">Terms &amp; <span>Conditions</span></h1>
          <div className="tc-hero-meta">
            <span>Last Updated: July 1, 2025</span>
            <span>Effective Immediately</span>
            <span>{sections.length} Sections</span>
          </div>
        </div>

        {/* ─── QUICK NAV ─── */}
        <div className="tc-quick-nav">
          <div className="tc-quick-nav-title">
            <i className="bi bi-list-ul me-2"></i>Table of Contents
          </div>
          <div className="tc-nav-grid">
            {quickNav.map((label, i) => (
              <a
                key={i}
                href={`#section-${i}`}
                className="tc-nav-link"
                onClick={(e) => scrollTo(e, i)}
              >
                <span className="tc-nav-num">{i < 9 ? `0${i + 1}` : i + 1}</span>
                {label}
              </a>
            ))}
          </div>
        </div>

        {/* ─── SECTIONS ─── */}
        <div className="py-2">
          {sections.map((sec, i) => (
            <div
              key={i}
              id={`section-${i}`}
              className="tc-section"
              ref={(el) => (sectionRefs.current[i] = el)}
            >
              <div className="tc-section-inner">
                {/* Number column */}
                <div className="tc-num-col">
                  <span className="tc-big-num">{String(i + 1).padStart(2, '0')}</span>
                  <div className="tc-num-line"></div>
                </div>
                {/* Content column */}
                <div>
                  <div className="tc-section-header">
                    <div className="tc-icon-wrap">
                      <i className={`bi ${sec.icon}`}></i>
                    </div>
                    <h2 className="tc-section-title">{sec.title}</h2>
                  </div>
                  <div className="tc-body">{sec.content}</div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* ─── AGREEMENT BANNER ─── */}
        <div className="tc-agreement">
          <i className="bi bi-patch-check-fill tc-agreement-icon"></i>
          <h4>You're All Caught Up</h4>
          <p>
            By using PrepAI, you acknowledge that you have read and agree to these Terms and
            Conditions in their entirety. These terms exist to protect both you and us.
          </p>
          <div className="tc-agree-btn" onClick={() => setShowModal(true)}>
            <i className="bi bi-check2-circle"></i>
            I Understand &amp; Agree
          </div>
        </div>

        <Footer />
      </div>

      {/* ─── MODAL ─────────────────────────────────────────────────── */}
      {showModal && (
        <div
          className="modal fade show d-block"
          tabIndex="-1"
          role="dialog"
          style={{ backgroundColor: 'rgba(0, 0, 0, 0.65)' }}
          onClick={(e) => { if (e.target === e.currentTarget) handleCancel() }}
        >
          <div className="modal-dialog modal-dialog-centered" role="document">
            <div
              className="modal-content border-0"
              style={{ borderRadius: '18px', overflow: 'hidden' }}
            >

              {!showSuccess ? (
                <>
                  {/* ── HEADER ── */}
                  <div className="modal-header border-0 pb-0 pt-4 px-4">
                    <div className="d-flex align-items-center gap-2">
                      <div
                        className="rounded-circle d-flex align-items-center justify-content-center flex-shrink-0"
                        style={{
                          width: 40,
                          height: 40,
                          background: 'rgba(99,102,241,0.12)',
                        }}
                      >
                        <i
                          className="bi bi-file-earmark-text"
                          style={{ color: '#6366f1', fontSize: 17 }}
                        ></i>
                      </div>
                      <div>
                        <h6 className="mb-0 fw-semibold" style={{ fontSize: 15 }}>
                          Terms &amp; Conditions
                        </h6>
                        <small className="text-muted">PrepAI — Last updated July 1, 2025</small>
                      </div>
                    </div>
                    <button
                      type="button"
                      className="btn-close"
                      onClick={handleCancel}
                      aria-label="Close"
                    />
                  </div>

                  {/* ── BODY ── */}
                  <div className="modal-body px-4 pt-3 pb-2">
                    {/* Summary box */}
                    <div
                      className="rounded-3 p-3 mb-3"
                      style={{
                        background: 'rgba(99,102,241,0.06)',
                        border: '1px solid rgba(99,102,241,0.15)',
                      }}
                    >
                      <p className="mb-0 small text-muted lh-base">
                        PrepAI is a free platform that uses AI to generate interview preparation
                        reports. All outputs are for personal use only. No data is retained between
                        sessions. By agreeing, you accept all terms outlined on this page.
                      </p>
                    </div>

                    {/* Checkbox 1 */}
                    <div className="form-check mb-3">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        id="tcCheck1"
                        checked={check1}
                        onChange={(e) => {
                          setCheck1(e.target.checked)
                          setShowWarn(false)
                        }}
                      />
                      <label
                        className="form-check-label small lh-base"
                        htmlFor="tcCheck1"
                        style={{ cursor: 'pointer' }}
                      >
                        I have read and understood the{' '}
                        <strong>Terms &amp; Conditions</strong>, including the AI disclaimer,
                        permitted use, and intellectual property sections.
                      </label>
                    </div>

                    {/* Checkbox 2 */}
                    <div className="form-check mb-3">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        id="tcCheck2"
                        checked={check2}
                        onChange={(e) => {
                          setCheck2(e.target.checked)
                          setShowWarn(false)
                        }}
                      />
                      <label
                        className="form-check-label small lh-base"
                        htmlFor="tcCheck2"
                        style={{ cursor: 'pointer' }}
                      >
                        I confirm I am at least <strong>13 years old</strong> and agree that
                        PrepAI reports are for personal interview preparation only and not a
                        professional assessment.
                      </label>
                    </div>

                    {/* Warning */}
                    {showWarn && (
                      <div className="alert alert-warning py-2 px-3 small mb-2 d-flex align-items-center gap-2">
                        <i className="bi bi-exclamation-triangle-fill flex-shrink-0"></i>
                        Please check both boxes to continue.
                      </div>
                    )}
                  </div>

                  {/* ── FOOTER ── */}
                  <div className="modal-footer border-0 px-4 pb-4 pt-2 gap-2">
                    <button
                      type="button"
                      className="btn btn-outline-secondary btn-sm px-4"
                      onClick={handleCancel}
                    >
                      Cancel
                    </button>
                    <button
                      type="button"
                      className="btn btn-primary btn-sm px-4"
                      onClick={handleAgree}
                    >
                      <i className="bi bi-check2-circle me-1"></i>
                      I Agree &amp; Accept
                    </button>
                  </div>
                </>
              ) : (
                /* ── SUCCESS ── */
                <div className="modal-body text-center py-5 px-4">
                  <div
                    className="rounded-circle d-flex align-items-center justify-content-center mx-auto mb-3"
                    style={{
                      width: 64,
                      height: 64,
                      background: 'rgba(34,197,94,0.12)',
                    }}
                  >
                    <i
                      className="bi bi-patch-check-fill"
                      style={{ color: '#22c55e', fontSize: 30 }}
                    ></i>
                  </div>
                  <h5 className="fw-semibold mb-2">You're all set!</h5>
                  <p className="text-muted small mb-4 lh-base">
                    Thank you for accepting PrepAI's Terms &amp; Conditions. You can now use all
                    features of the platform freely.
                  </p>
                  <button
                    type="button"
                    className="btn btn-success btn-sm px-5"
                    onClick={handleOk}
                  >
                    OK
                  </button>
                </div>
              )}

            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default TermsAndCondition